@startuml class_diagram
skinparam monochrome true
skinparam shadowing false
' クラスを定義

class ユーザー{
    string ユーザーID
    string パスワード
}

class 生徒{
    string 生徒ID
    **string ユーザーID**
    int 性別
    string 名前
}
class グループ{
    int クラスID
    string クラス名
    int 年度
    **string ユーザーID**
}

class 座席配置{
    int 座席配置ID
    **int クラスID**
    **string ユーザーID**
    string 座席配置名
    date 開始期間
    date 終了期間
    date 作成日
}
class 生徒と座席の関連{
    int 生徒と座席の関連ID
    **int 座席配置ID**
    **string 生徒ID**
    int 座席位置
}
class 評価{
    int 評価ID
    **string 生徒ID**
    **int 授業ID**
    boolean 出欠
    int 観点１
    int 観点２
    int 観点３
    string 評価のコメント
    int 座席位置
    **string ユーザーID**
}

class 授業{
    int 授業ID
    **int 座席配置ID**
    date 授業日
    int 時限
    string 授業コメント
}


' 関係を定義
'left to right direction

座席配置 "1"--"1...*" 生徒と座席の関連
評価 "1...*" -- "1"  授業
生徒 "1...*" -- "1...*" グループ
生徒"1" -- "0...*" 評価
ユーザー"1" -- "0...*" 生徒 :▼登録する
ユーザー"1" -- "0...*" 座席配置 :▼登録する
ユーザー"1" -- "0...*" グループ :▼登録する
座席配置 "0...*" -- "1"グループ
生徒と座席の関連 "1...*" -- "1" 生徒
評価 "0...*" -- "1" ユーザー :▼登録する
授業 "0...*"-- "1"グループ
座席配置 "1"--"1...*" 評価
授業 "1"-- "1" 座席配置
' umlの終了を宣言
@enduml