@startuml class_diagram
skinparam monochrome true
skinparam shadowing false
' クラスを定義

class ユーザー{
    ID
    パスワード
}

class 生徒{
    生徒ID
    ユーザーID
    性別
    名前
}
class クラス{
    クラスID
    クラス名
    年度
    ユーザーID
}
class メンバー{
    クラスID
    生徒ID
}
class 座席配置情報{
    座席配置ID
    クラスID
    ユーザーID
    開始期間
    終了期間
}
class 生徒座席配置{
    座席配置ID
    生徒ID
    座席
}
class 評価{
    評価ID
    生徒ID
    授業ID
    出欠
    観点１
    観点２
    観点３
    評価のコメント
    座席
}

class 授業{
    授業ID
    作成日
    授業日
    授業コメント
}


' 関係を定義
'left to right direction

座席配置情報 "1"--"1...*" 生徒座席配置
評価 "1...*" -- "1"  授業
クラス "1" -- "1...*" メンバー
生徒 "1" -- "1...*" メンバー
生徒"1" -- "1" 評価
ユーザー"1" -- "0...*" 生徒
ユーザー"1" -- "0...*" 座席配置情報
ユーザー"1" -- "0...*" クラス
座席配置情報 "1" -- "1"クラス
生徒座席配置 "1...*" -- "1" 生徒

' umlの終了を宣言
@enduml