@startuml class_diagram
skinparam monochrome true
skinparam shadowing false
' クラスを定義

class ユーザー{
    string ID
    string パスワード
}

class 生徒{
    string 生徒ID
    string ユーザーID
    int 性別
    string 名前
}
class クラス{
    int クラスID
    string クラス名
    int 年度
    string ユーザーID
}
class メンバー{
    int メンバーID
    int クラスID
    string 生徒ID
}
class 座席配置情報{
    int 座席配置情報ID
    int クラスID
    string ユーザーID
    date 開始期間
    date 終了期間
}
class 座席配置{
    int 座席配置ID
    int 座席配置情報ID
    string 生徒ID
    int 座席
}
class 評価{
    int 評価ID
    string 生徒ID
    int 授業ID
    int 出欠
    int 観点１
    int 観点２
    int 観点３
    string 評価のコメント
    int 座席
    string ユーザーID
}

class 授業{
    int 授業ID
    date 作成日
    date 授業日
    int 時限
    string 授業コメント
}


' 関係を定義
'left to right direction

座席配置情報 "1"--"1...*" 座席配置
評価 "1...*" -- "1"  授業
クラス "1" -- "1...*" メンバー
生徒 "1" -- "1...*" メンバー
生徒"1" -- "1" 評価
ユーザー"1" -- "0...*" 生徒
ユーザー"1" -- "0...*" 座席配置情報
ユーザー"1" -- "0...*" クラス
座席配置情報 "1" -- "1"クラス
座席配置 "1...*" -- "1" 生徒
評価 "0...*" -- "1" ユーザー
' umlの終了を宣言
@enduml